[package]
name = "pdal-capi"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "C ABI for PDAL Rust port spike."

[lib]
crate-type = ["cdylib", "staticlib", "rlib"]



[dependencies]
chrono = "0.4.44"
pdal-core = { path = "../pdal-core" }
pdal-filters = { path = "../pdal-filters" }
pdal-io = { path = "../pdal-io" }
pdal-kernels = { path = "../pdal-kernels" }
pdal-native = { path = "../pdal-native" }
serde_json = "1"
glob = "0.3"
zstd = "0.13"

[dev-dependencies]
tempfile = "3.27.0"
