[package]
name = "pdal-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "pdal-rs"
path = "src/main.rs"

[dependencies]
pdal-capi = { path = "../pdal-capi" }
pdal-core = { path = "../pdal-core" }
pdal-kernels = { path = "../pdal-kernels" }
glob = "0.3"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[dev-dependencies]
pdal-io = { path = "../pdal-io" }
