use super::{filename, option};
use serde_json::json;

pub(super) fn options(stage_name: &str) -> Vec<serde_json::Value> {
    match stage_name {
        "writers.null" => Vec::new(),
        "writers.bpf" => vec![
            filename(),
            option("compression", "Compress output data.", Some(json!(false))),
            option(
                "bundledfile",
                "Additional file to bundle inside the BPF output.",
                None,
            ),
        ],
        "writers.fbi" => vec![filename()],
        "writers.gltf" => vec![
            filename(),
            option("metallic", "Material metallic factor.", Some(json!(0.0))),
            option("roughness", "Material roughness factor.", Some(json!(0.0))),
            option("red", "Default material red channel.", Some(json!(0.0))),
            option("green", "Default material green channel.", Some(json!(0.0))),
            option("blue", "Default material blue channel.", Some(json!(0.0))),
            option("alpha", "Default material alpha channel.", Some(json!(1.0))),
            option(
                "double_sided",
                "Write double-sided mesh materials.",
                Some(json!(false)),
            ),
            option("colors", "Write vertex colors.", Some(json!(false))),
            option("normals", "Write vertex normals.", Some(json!(false))),
        ],
        "writers.sbet" => vec![
            filename(),
            option(
                "angles_are_degrees",
                "Convert angular fields from degrees to radians.",
                Some(json!(true)),
            ),
        ],
        "writers.spz" => vec![
            filename(),
            option(
                "antialiased",
                "Mark the output Gaussian splats as antialiased.",
                Some(json!(false)),
            ),
            option(
                "coordinate_orientation",
                "Input coordinate orientation name.",
                None,
            ),
        ],
        "writers.copc" => vec![
            filename(),
            option(
                "minor_version",
                "LAS minor version (COPC requires 4).",
                Some(json!(4)),
            ),
            option("scale_x", "X coordinate scale.", None),
            option("scale_y", "Y coordinate scale.", None),
            option("scale_z", "Z coordinate scale.", None),
            option("offset_x", "X coordinate offset.", None),
            option("offset_y", "Y coordinate offset.", None),
            option("offset_z", "Z coordinate offset.", None),
            option("system_id", "LAS system identifier.", None),
            option("software_id", "LAS generating software identifier.", None),
            option("project_id", "LAS project GUID.", None),
        ],
        "writers.las" | "writers.laz" => vec![
            filename(),
            option("compression", "Compress output data.", Some(json!(false))),
            option("point_format", "LAS point format ID.", Some(json!(3))),
            option("dataformat_id", "LAS point format ID.", None),
            option("format", "LAS point format ID.", None),
            option("minor_version", "LAS minor version.", None),
            option("scale_x", "X coordinate scale.", None),
            option("scale_y", "Y coordinate scale.", None),
            option("scale_z", "Z coordinate scale.", None),
            option("offset_x", "X coordinate offset.", None),
            option("offset_y", "Y coordinate offset.", None),
            option("offset_z", "Z coordinate offset.", None),
            option("filesource_id", "LAS file source ID.", None),
            option("system_id", "LAS system identifier.", None),
            option("software_id", "LAS generating software identifier.", None),
            option("creation_doy", "LAS creation day of year.", None),
            option("creation_year", "LAS creation year.", None),
            option("project_id", "LAS project GUID.", None),
        ],
        "writers.nitf" => vec![
            filename(),
            option("clevel", "NITF complexity level.", Some(json!("03"))),
            option("stype", "NITF system type.", Some(json!("BF01"))),
            option("ostaid", "Originating station ID.", Some(json!("PDAL"))),
            option("ftitle", "File title (defaults to filename).", None),
            option("fsclas", "File classification.", Some(json!("U"))),
            option("oname", "Originator name.", None),
            option("ophone", "Originator phone.", None),
            option("fsctlh", "File control/handling.", None),
            option("fsclsy", "File classification system.", None),
            option("fscltx", "File classification text.", None),
            option("isclas", "Image classification.", Some(json!("U"))),
            option("idatim", "Image date/time (YYYYMMDDHHMMSS).", None),
            option("iid2", "Image identifier 2.", None),
            option(
                "aimidb",
                "AIMIDB field overrides (repeatable, name:value).",
                None,
            ),
            option(
                "acftb",
                "ACFTB field overrides (repeatable, name:value).",
                None,
            ),
        ],
        "writers.text" => vec![
            filename(),
            option("order", "Comma-separated output dimension order.", None),
            option(
                "precision",
                "Floating-point output precision.",
                Some(json!(6)),
            ),
            option("delimiter", "Output delimiter.", Some(json!(","))),
            option(
                "quote_header",
                "Quote output header fields.",
                Some(json!(true)),
            ),
        ],
        "writers.pcd" => vec![
            filename(),
            option("order", "Comma-separated output dimension order.", None),
            option(
                "precision",
                "Floating-point output precision.",
                Some(json!(2)),
            ),
            option(
                "compression",
                "PCD storage mode: ascii or binary.",
                Some(json!("ascii")),
            ),
            option(
                "keep_unspecified",
                "Write dimensions not listed in the output order.",
                Some(json!(true)),
            ),
        ],
        "writers.ply" => vec![
            filename(),
            option("storage_mode", "PLY storage mode.", Some(json!("ascii"))),
            option("dims", "Comma-separated dimension list.", None),
            option(
                "sized_types",
                "Use sized PLY type names.",
                Some(json!(true)),
            ),
            option("precision", "Floating-point output precision.", None),
            option("faces", "Write triangular mesh faces.", Some(json!(false))),
        ],
        "writers.ogr" => vec![
            filename(),
            option("ogrdriver", "OGR driver name.", Some(json!("GeoJSON"))),
            option("attr_dims", "Comma-separated attribute dimensions.", None),
            option("multicount", "Points per feature.", Some(json!(1))),
            option("measure_dim", "Dimension to use as a measure value.", None),
        ],
        "writers.gdal" => vec![
            filename(),
            option(
                "resolution",
                "Cell edge size in X/Y units.",
                Some(json!(1.0)),
            ),
            option(
                "radius",
                "Radius from each cell center for source points.",
                None,
            ),
            option("power", "IDW weighting power.", Some(json!(1.0))),
            option(
                "gdaldriver",
                "GDAL writer driver name.",
                Some(json!("GTiff")),
            ),
            option(
                "output_type",
                "Raster statistic names to write.",
                Some(json!("all")),
            ),
            option(
                "dimension",
                "Point dimension to rasterize.",
                Some(json!("Z")),
            ),
            option(
                "data_type",
                "Raster cell data type.",
                Some(json!("float64")),
            ),
            option("nodata", "No-data value.", Some(json!(-9999.0))),
            option(
                "binmode",
                "Assign points directly to cells.",
                Some(json!(false)),
            ),
            option(
                "window_size",
                "Cell distance for fallback interpolation.",
                Some(json!(0)),
            ),
            option("allow_empty", "Allow empty output.", Some(json!(false))),
            option("origin_x", "Fixed grid X origin.", None),
            option("origin_y", "Fixed grid Y origin.", None),
            option("width", "Fixed grid width in cells.", None),
            option("height", "Fixed grid height in cells.", None),
            option("bounds", "Deprecated fixed grid bounds.", None),
            option("override_srs", "Spatial reference to apply.", None),
            option(
                "default_srs",
                "Spatial reference to apply when input has none.",
                None,
            ),
            option("metadata", "Comma-separated GDAL metadata items.", None),
        ],
        "writers.raster" => vec![
            filename(),
            option(
                "gdaldriver",
                "GDAL writer driver name.",
                Some(json!("GTiff")),
            ),
            option("rasters", "Comma-separated raster names to write.", None),
            option("nodata", "No-data value.", None),
        ],
        _ => Vec::new(),
    }
}
